#!/usr/bin/env python3
# -*- coding: utf-8 -*-

##############################################################################
# Owner     : Expleo Group
# Author    : Tarek AZAIZ
# Project   : Drones Attack Demonstrator
# Subject   : Useful tools to manipulate CSV generated by aircrack
# Version   : 0.1
# Created   : 2022/03/31
# Modified  : 2022/05/04
##############################################################################

import pandas

from pwn import *


def get_clients_bssid(csv_dump):
    """
    load the CSV dump file of the targeted network and return 
    the clients BBSID list
    """
    # list that will be returned as result
    clients_bssid = []
    # load the CSV dump file in a pandas dataframe
    df = pandas.read_csv(csv_dump, header=None)
    # separate the panda dataframe in two sections :
    # the first for the networks (begin by 'BSSID')
    # the second for the clients stations (begins by 'Station MAC')
    table_names = ['BSSID', 'Station MAC']
    groups = df[0].isin(table_names).cumsum()
    tables = {g.iloc[0,0]: g.iloc[1:] for k,g in df.groupby(groups)}

    # calculate the row indexes to access to clients list
    (nw,cli) = tables.items()
    nb_nw = len(nw[1]) # number of networks
    nb_cli = len(cli[1]) # number of clients
    first_cli_ind = nb_nw+2 # first "clients" row index
    last_cli_ind = first_cli_ind + nb_cli # last "clients" row index
    clients_table = cli[1] # clients table
    bssid_col = clients_table[0] # bssid col in the clients table
    
    # finaly, browse the bssid clients col and append to result
    for i in range (nb_nw+2, nb_nw+2+nb_cli):
        clients_bssid.append(bssid_col[i])

    return clients_bssid


